name: aws

on:
  push:
    branches:
      - master
  
permissions:
  id-token: write
  contents: read

env:
  REGISTRY: ${{secrets.AWS_ECR_REGISTRY}}

jobs:
  build-docker:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    outputs:
      docker-image: ${{ steps.build-image.outputs.DOCKER_IMAGE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Assume Role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-southeast-2
          role-to-assume: ${{ secrets.AWS_ECR_ROLE }}
          role-duration-seconds: 3600
          role-skip-session-tagging: true
          mask-aws-account-id: false

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker Image
        id: build-image
        run: |
          export IMAGE_TAG=backend-$(date +%Y%m%d)
          docker build --target production -t "${{secrets.AWS_ECR_REGISTRY}}/jkos-interview-backend:prod" ./backend
          docker tag "${{secrets.AWS_ECR_REGISTRY}}/jkos-interview-backend:prod" "${{secrets.AWS_ECR_REGISTRY}}/jkos-interview-backend:${IMAGE_TAG}"
          docker push "${{secrets.AWS_ECR_REGISTRY}}/jkos-interview-backend:${IMAGE_TAG}"
          echo "DOCKER_IMAGE=jkos-interview-backend:${IMAGE_TAG}" >> $GITHUB_OUTPUT

  render-task-def:
    needs:
      - build-docker
    runs-on: ubuntu-latest
    environment: production
    outputs:
      task-def-filename: ${{ steps.set-filename.outputs.filename }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get task-definition file path for
        id: init
        run: |
          echo "task-definition=backend/deploy/backend-prod.json" >> $GITHUB_OUTPUT
          echo "container-name=app" >> $GITHUB_OUTPUT

      - name: Inject secrets into task definition
        run: |
          echo "=== BEFORE ==="
          cat ${{ steps.init.outputs.task-definition }}
          sed -i "s|\$TASK_ROLE_ARN|${{ secrets.TASK_ROLE_ARN }}|g" ${{ steps.init.outputs.task-definition }}
          sed -i "s|\$AWS_ECR_REGISTRY|${{ secrets.AWS_ECR_REGISTRY }}|g" ${{ steps.init.outputs.task-definition }}
          echo "=== AFTER ==="
          cat ${{ steps.init.outputs.task-definition }}

      - name: Render Task Definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ steps.init.outputs.task-definition }}
          container-name: ${{ steps.init.outputs.container-name }}
          image: ${{secrets.AWS_ECR_REGISTRY}}/${{ needs.build-docker.outputs.docker-image }}

      - name: debug
        run: cat ${{ steps.task-def.outputs.task-definition }}

      - name: Temporarily save task-definition
        uses: actions/upload-artifact@v6
        with:
          name: task-definition.json
          path: ${{ steps.task-def.outputs.task-definition }}
          retention-days: 1

      - name: set task-def filename
        id: set-filename
        run: echo "filename=$(basename ${{ steps.task-def.outputs.task-definition }})" >> $GITHUB_OUTPUT

  deploy-prod:
    if: github.ref == 'refs/heads/master'
    needs:
      - render-task-def
    runs-on: ubuntu-latest

    environment:
      name: production
      # url: http://
    steps:
      - name: Configure AWS Assume Role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-southeast-2
          role-to-assume: ${{ secrets.AWS_ECR_ROLE }}
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Retrieve saved task-definition
        uses: actions/download-artifact@v6
        id: download
        with:
          name: task-definition.json

      - name: Deploy ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          cluster: backend-prod
          service: backend-prod-web
          task-definition: ${{needs.render-task-def.outputs.task-def-filename}}
          force-new-deployment: true

      - name: DB migration
        run: |
          aws ecs run-task \
            --cluster backend-prod \
            --task-definition backend-prod \
            --overrides '{ "containerOverrides": [ { "name": "app", "command": [ "npm", "run", "migration:run" ] } ]}'
